# Generated by Django 5.2.6 on 2025-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('model', '3D Model')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
