# Generated by Django 5.2.6 on 2025-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_type_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('model', '3D Model'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
