# Generated by Django 5.2.6 on 2025-10-21 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_uploaded_at_asset_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
