# Generated by Django 5.2.6 on 2025-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='average_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='difference_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dominant_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='perceptual_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
